<Project Sdk="Microsoft.NET.Sdk">

  <ItemGroup>
    <FrameworkReference Include="Microsoft.AspNetCore.App" />
  </ItemGroup>

  <ItemGroup>
    <Compile Remove="MapEntities\Status\**" />
    <EmbeddedResource Remove="MapEntities\Status\**" />
    <None Remove="MapEntities\Status\**" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\EEaseWebAPI.Domain\EEaseWebAPI.Domain.csproj" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="AutoMapper" />
    <PackageReference Include="FluentValidation" />
    <PackageReference Include="FluentValidation.DependencyInjectionExtensions" />
    <PackageReference Include="MediatR" />
    <PackageReference Include="Microsoft.AspNetCore.Identity.EntityFrameworkCore" />
    <PackageReference Include="Microsoft.EntityFrameworkCore" />
    <PackageReference Include="Microsoft.Extensions.Caching.Memory" />
    <PackageReference Include="Microsoft.Extensions.Options.ConfigurationExtensions" />
    <PackageReference Include="Newtonsoft.Json" />
    <PackageReference Include="Swashbuckle.AspNetCore.SwaggerGen" />
  </ItemGroup>

</Project>
