<Project Sdk="Microsoft.NET.Sdk">

  <ItemGroup>
    <ProjectReference Include="..\..\Core\EEaseWebAPI.Application\EEaseWebAPI.Application.csproj" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="MailKit" />
    <PackageReference Include="MimeKit" />
    <PackageReference Include="Microsoft.Extensions.Http" />
    <PackageReference Include="System.IdentityModel.Tokens.Jwt" />
  </ItemGroup>


  <ItemGroup>
    <EmbeddedResource Include="Templates\*.html" />
  </ItemGroup>

</Project>
